FROM buildkite/puppeteer:latest

COPY test test
COPY src src

RUN npm install \
  @types/react \
  @types/react-dom \
  parcel-bundler \
  react \
  react-dom \
  typescript

WORKDIR /

CMD /node_modules/.bin/parcel serve -p 1234 /test/index.html

HEALTHCHECK --interval=5s --timeout=10s --retries=10 \
  CMD curl -f http://localhost:1234
