FROM buildkite/puppeteer:latest

WORKDIR /

# NOTE: mounted as a volume so we don't need to keep rebuilding the image
#COPY dist dist

CMD cd dist && python3 -m http.server 1234

HEALTHCHECK --interval=5s --timeout=10s --retries=10 \
  CMD curl -f http://localhost:1234
